---
apiVersion: v1
kind: ConfigMap

metadata:
  name: api-env

data:
  DEBUG: "True"
  PORT: "5000"
  LOG_LEVEL: DEBUG
  DB_HOST: "postgres.internal.dev.pilgrimagesoftware.com"
  DB_PORT: "5432"
  DB_USER: statesman
  DB_NAME: statesman
  REDIS_HOST: redis.statesman.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_DB: "7"
  SENTRY_ENV: Development
  BUILD_INFO_PATH: /app/build-info.json
  RABBITMQ_HOST: "rabbitmq.statesman.svc.cluster.local"
  RABBITMQ_PORT: "5672"
  RABBITMQ_VHOST: "statesman"
  RABBITMQ_EXCHANGE: ""
  RABBITMQ_USER: "statesman-api"
  RABBITMQ_QUEUE: "api"
