---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule

metadata:
  name: statesman

spec:
  host: store.statesman.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
