---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule

metadata:
  name: store

spec:
  host: store-v1.statesman.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
