---
# See more at https://istio.io/docs/reference/config/networking/gateway/
apiVersion: networking.istio.io/v1alpha3
kind: Gateway

metadata:
  name: statesman-gateway

spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*/api.statesman.pilgrimagesoftware.com"
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "*/api.statesman.pilgrimagesoftware.com"
      tls:
        mode: PASSTHROUGH
    # serverCertificate: /etc/istio/ingressgateway-certs/sweetrpg-io-crt.pem
    # privateKey: /etc/istio/ingressgateway-certs/sweetrpg-io-key.pem
