---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: statesman

resources:
  - configmaps.yaml
  - ../../base
  - secrets.yaml
  - destination-rules.yaml
  - virtual-service.yaml
  - gateway.yaml
  - ingress-route.yaml
  - middlewares.yaml
