---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: statesman

resources:
  - ../../base
  - configmaps.yaml
  - secrets.yaml
  - destination-rules.yaml
  - virtual-service.yaml
  - gateway.yaml
  - ingress.yaml
  - middlewares.yaml
  - hpa.yaml
  - pdb.yaml

commonLabels:
  app: store
  version: v1
