---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: statesman
  namespace: statesman

spec:
  refreshInterval: 1h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: statesman
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /critical-failure/statesman/app/app
