---
# See more at https://istio.io/docs/reference/config/networking/virtual-service/
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService

metadata:
  name: statesman

spec:
  hosts:
    - store.statesman.pilgrimagesoftware.com
  gateways:
    - statesman-gateway
  http:
    - route:
        - destination:
            host: store.statesman.svc.cluster.local
            port:
              number: 8899
  tls:
    - match:
        - port: 443
          sniHosts:
            - store.statesman.pilgrimagesoftware.com
      route:
        - destination:
            host: store.statesman.svc.cluster.local
            port:
              number: 8899
