version: "3.1"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: ../..
    env_file: ../../.env
    command: flask run
    ports:
      - "5000:5000"
    networks:
      - statesman-store

  redis:
    image: redis:6
    networks:
      - statesman-store

networks:
  statesman-store: {}
