---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: store

spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: store
      version: v1
  template:
    metadata:
      labels:
        app: store
        version: v1
    spec:
      serviceAccountName: store
      containers:
        - name: store
          image: ghcr.io/pilgrimagesoftware/statesman-store:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: store
          envFrom:
            - configMapRef:
                name: common
            - configMapRef:
                name: store
            - configMapRef:
                name: store-env
            - secretRef:
                name: common
            - secretRef:
                name: store
          env:
            - name: POD
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: "20m"
              memory: "55Mi"
            limits:
              cpu: "50m"
              memory: "200Mi"
          livenessProbe:
            httpGet:
              path: /health/ping
              port: 5000
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ping
              port: 5000
            initialDelaySeconds: 30
            timeoutSeconds: 5
      restartPolicy: Always
