---
kind: Service
apiVersion: v1

metadata:
  name: store-v1

spec:
  type: ClusterIP
  selector:
    app: store
    version: v1
  ports:
    - name: store
      port: 5000
      targetPort: store
      protocol: TCP
