---
# See more at https://istio.io/docs/reference/config/networking/service-entry/
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry

metadata:
  name: slack

spec:
  hosts:
    - "*.slack.com"
  ports:
    - number: 80
      name: http
      protocol: HTTP
    - number: 443
      name: https
      protocol: HTTPS

---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry

metadata:
  name: newrelic

spec:
  hosts:
    - "*.newrelic.com"
  ports:
    - name: api
      number: 443
      protocol: HTTPS
      targetPort: 443
  resolution: NONE

---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry

metadata:
  name: sentry-io

spec:
  hosts:
    - "*.sentry.io"
  ports:
    - name: api
      number: 443
      protocol: HTTPS
      targetPort: 443
  resolution: NONE

---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry

metadata:
  name: postgres

spec:
  hosts:
    - "postgres.internal.dev.pilgrimagesoftware.com"
  ports:
    - name: pgsql
      number: 5432
      protocol: TCP
      targetPort: 5432
  resolution: NONE
